"""Small DSL for building Geometry Nodes trees from Python.

Every MoBlend node group is generated by code (never shipped as a .blend), so
the add-on works in any file and rebuilds its groups when GROUP_VERSION bumps.
"""

from collections import deque

import bpy

from ..catalog import KEY_VERSION

# Bump when any group's nodes or interface change; stale groups are rebuilt in place.
GROUP_VERSION = 24

_SOCKET_TYPES = {
    "GEOMETRY": "NodeSocketGeometry", "FLOAT": "NodeSocketFloat", "INT": "NodeSocketInt",
    "BOOL": "NodeSocketBool", "VECTOR": "NodeSocketVector", "ROTATION": "NodeSocketRotation",
    "MATRIX": "NodeSocketMatrix", "COLOR": "NodeSocketColor", "STRING": "NodeSocketString",
    "OBJECT": "NodeSocketObject", "COLLECTION": "NodeSocketCollection", "MATERIAL": "NodeSocketMaterial",
    "FONT": "NodeSocketFont", "MENU": "NodeSocketMenu", "SOUND": "NodeSocketSound", "IMAGE": "NodeSocketImage",
}


def S(name, kind, default=None, lo=None, hi=None, subtype=None, desc="", hide_value=False):
    """Socket spec for a group interface."""
    return {"name": name, "kind": kind, "default": default, "lo": lo, "hi": hi, "subtype": subtype, "desc": desc,
            "hide_value": hide_value}


def _pick(sockets, key):
    """Socket by index (among enabled ones), name or identifier. O(sockets)."""
    if isinstance(key, int):
        return [s for s in sockets if s.enabled][key]
    fallback = None
    for s in sockets:
        if s.name == key or s.identifier == key:
            if s.enabled:
                return s
            fallback = fallback or s
    if fallback is None:
        raise KeyError(f"{key!r} not in {[s.name for s in sockets if s.enabled]}")
    return fallback


def out(node, key=0):
    return _pick(node.outputs, key)


class B:
    """Builder bound to one node tree. Shorthands return output sockets."""

    def __init__(self, tree):
        self.t = tree

    # -- generic ---------------------------------------------------------
    def node(self, idname, inputs=None, **props):
        n = self.t.nodes.new(idname)
        for k, v in props.items():  # props first: data_type etc. change the sockets
            setattr(n, k, v)
        for k, v in (inputs or {}).items():
            self.set(n, k, v)
        return n

    def set(self, n, key, v):
        """Link a socket/node into input `key`, or set its value. None leaves it alone."""
        if v is not None:
            self.assign(_pick(n.inputs, key), v)

    def assign(self, sock, v):
        if isinstance(v, bpy.types.NodeSocket):
            self.t.links.new(v, sock)
        elif isinstance(v, bpy.types.Node):
            self.t.links.new(out(v), sock)
        else:
            sock.default_value = v

    def link(self, a, b):
        self.t.links.new(a, b)

    def group(self, tree, inputs=None):
        n = self.node("GeometryNodeGroup")
        n.node_tree = tree
        for k, v in (inputs or {}).items():
            self.set(n, k, v)
        return n

    def inp(self, idname, key=0):
        return out(self.node(idname), key)

    # -- math --------------------------------------------------------------
    def math(self, op, a, b=None, c=None):
        n = self.node("ShaderNodeMath", operation=op)
        for i, v in enumerate((a, b, c)):
            self.set(n, i, v)
        return n.outputs[0]

    def vmath(self, op, a, b=None, c=None, scale=None):
        n = self.node("ShaderNodeVectorMath", operation=op)
        vec_ins = [s for s in n.inputs if s.enabled and s.type == "VECTOR"]
        for s, v in zip(vec_ins, (a, b, c), strict=False):  # ops take 1-3 vectors
            if v is not None:
                self.assign(s, v)
        if scale is not None:
            self.assign(_pick(n.inputs, "Scale"), scale)
        return out(n)

    def at_least(self, v, lo=1.0):
        return self.math("MAXIMUM", v, lo)

    def steps(self, count):
        """max(count - 1, 1): divisor that spreads `count` items over [0, 1]."""
        return self.at_least(self.math("SUBTRACT", count, 1.0))

    def combine(self, x=0.0, y=0.0, z=0.0):
        return self.node("ShaderNodeCombineXYZ", {"X": x, "Y": y, "Z": z}).outputs[0]

    def separate(self, v):
        n = self.node("ShaderNodeSeparateXYZ", {"Vector": v})
        return n.outputs["X"], n.outputs["Y"], n.outputs["Z"]

    def mix(self, dtype, fac, a, b, clamp=True):
        n = self.node("ShaderNodeMix", {"Factor": fac, "A": a, "B": b}, data_type=dtype, clamp_factor=clamp)
        return out(n, "Result")

    def switch(self, dtype, cond, false, true):
        return self.node("GeometryNodeSwitch", {"Switch": cond, "False": false, "True": true},
                         input_type=dtype).outputs[0]

    def index_switch(self, dtype, index, values):
        """Pick values[index]. With a single-value index only the chosen branch is evaluated."""
        n = self.node("GeometryNodeIndexSwitch", data_type=dtype)
        for _ in range(len(values) - len(n.index_switch_items)):
            n.index_switch_items.new()
        self.set(n, "Index", index)
        items = [s for s in n.inputs if s.identifier.startswith("Item_")]
        for s, v in zip(items, values, strict=True):
            self.assign(s, v)
        return n.outputs[0]

    def menu(self, items, menu_input, dtype="INT", values=None):
        """Menu Switch mapping item names to values (0..n-1 by default), driven by `menu_input`."""
        n = self.node("GeometryNodeMenuSwitch", data_type=dtype)
        n.enum_items.clear()
        for name in items:
            n.enum_items.new(name)
        item_socks = [s for s in n.inputs if s.type not in ("MENU", "CUSTOM")]
        for s, v in zip(item_socks, values if values is not None else range(len(items)), strict=True):
            self.assign(s, v)
        self.link(menu_input, _pick(n.inputs, "Menu"))
        return n.outputs[0]

    def map_range(self, v, fmin, fmax, tmin=0.0, tmax=1.0, interp="LINEAR"):
        n = self.node("ShaderNodeMapRange", {"Value": v, "From Min": fmin, "From Max": fmax, "To Min": tmin,
                                             "To Max": tmax}, data_type="FLOAT", interpolation_type=interp,
                      clamp=True)
        return out(n, "Result")

    def rand(self, dtype, lo, hi, seed=0):
        n = self.node("FunctionNodeRandomValue", {"Min": lo, "Max": hi, "Seed": seed}, data_type=dtype)
        return out(n, "Value")

    def compare(self, a, b, op="EQUAL", dtype="INT"):
        return self.node("FunctionNodeCompare", {"A": a, "B": b}, data_type=dtype, operation=op).outputs[0]

    def bool_not(self, v):
        return self.node("FunctionNodeBooleanMath", {0: v}, operation="NOT").outputs[0]

    # -- rotations & matrices ---------------------------------------------
    def euler_to_rot(self, v):
        return self.node("FunctionNodeEulerToRotation", {"Euler": v}).outputs[0]

    def transform_point(self, v, matrix):
        return self.node("FunctionNodeTransformPoint", {"Vector": v, "Transform": matrix}).outputs[0]

    def to_local(self, v, matrix):
        """Point `v` expressed in the space of `matrix` (e.g. an effector's)."""
        inv = self.node("FunctionNodeInvertMatrix", {"Matrix": matrix}).outputs["Matrix"]
        return self.transform_point(v, inv)

    def split_transform(self, matrix):
        n = self.node("FunctionNodeSeparateTransform", {"Transform": matrix})
        return out(n, "Translation"), out(n, "Rotation"), out(n, "Scale")

    def instance_trs(self):
        """(translation, rotation, scale) fields of the current instance."""
        return self.split_transform(self.inp("GeometryNodeInstanceTransform"))

    def combine_transform(self, t=None, r=None, s=None):
        return self.node("FunctionNodeCombineTransform", {"Translation": t, "Rotation": r, "Scale": s}).outputs[0]

    # -- inputs & common chains -------------------------------------------
    def index(self):
        return self.inp("GeometryNodeInputIndex")

    def position(self):
        return self.inp("GeometryNodeInputPosition")

    def seconds(self):
        return self.inp("GeometryNodeInputSceneTime", "Seconds")

    def noise4d(self, vector, w, detail=0.0):
        """Noise texture node (use outputs Factor / Color)."""
        return self.node("ShaderNodeTexNoise", {"Vector": vector, "W": w, "Detail": detail}, noise_dimensions="4D")

    def object_geometry(self, obj, space="RELATIVE", realize=True):
        """Geometry of an object input; realized unless `realize` is False (keeps a cloner's instances)."""
        geo = out(self.node("GeometryNodeObjectInfo", {"Object": obj}, transform_space=space), "Geometry")
        return self.node("GeometryNodeRealizeInstances", {"Geometry": geo}).outputs[0] if realize else geo

    def join(self, *geos):
        n = self.node("GeometryNodeJoinGeometry")
        for g in geos:
            if g is not None:
                self.link(g, n.inputs[0])
        return n.outputs[0]

    def instance_count(self, geo):
        n = self.node("GeometryNodeAttributeDomainSize", {"Geometry": geo}, component="INSTANCES")
        return out(n, "Instance Count")

    def named(self, name, dtype):
        return self.node("GeometryNodeInputNamedAttribute", {"Name": name}, data_type=dtype).outputs["Attribute"]

    def store(self, geo, name, value, dtype, domain):
        return self.node("GeometryNodeStoreNamedAttribute", {"Geometry": geo, "Name": name, "Value": value},
                         data_type=dtype, domain=domain).outputs[0]


def new_group(name, inputs, outputs, desc=""):
    """Create (or reset in place) a geometry node group with the given interface."""
    ng = bpy.data.node_groups.get(name)
    if ng is None:
        ng = bpy.data.node_groups.new(name, "GeometryNodeTree")
    else:
        ng.nodes.clear()
        ng.interface.clear()
    ng.description = desc
    for spec in inputs:
        _add_socket(ng, spec, "INPUT")
    for spec in outputs:
        _add_socket(ng, spec, "OUTPUT")
    ng[KEY_VERSION] = GROUP_VERSION
    return ng, ng.nodes.new("NodeGroupInput"), ng.nodes.new("NodeGroupOutput"), B(ng)


def _add_socket(ng, spec, in_out):
    s = ng.interface.new_socket(spec["name"], in_out=in_out, socket_type=_SOCKET_TYPES[spec["kind"]])
    s.description = spec["desc"]
    if spec["subtype"]:
        s.subtype = spec["subtype"]
    if spec["default"] is not None:
        s.default_value = spec["default"]
    if spec["lo"] is not None:
        s.min_value = spec["lo"]
    if spec["hi"] is not None:
        s.max_value = spec["hi"]
    s.hide_value = spec["hide_value"]
    return s


def set_menu_defaults(ng, defaults):
    """Menu interface defaults can only be set once the menu is linked. O(interface items)."""
    for item in ng.interface.items_tree:
        if item.item_type == "SOCKET" and item.in_out == "INPUT" and item.name in defaults:
            item.default_value = defaults[item.name]


def arrange(ng):
    """Columns by longest link distance from the sources: Kahn's topological order, O(nodes + links)."""
    nodes = list(ng.nodes)
    succ = {n: [] for n in nodes}
    indeg = dict.fromkeys(nodes, 0)
    for link in ng.links:
        succ[link.from_node].append(link.to_node)
        indeg[link.to_node] += 1
    depth = dict.fromkeys(nodes, 0)
    queue = deque(n for n in nodes if indeg[n] == 0)
    while queue:
        n = queue.popleft()
        for m in succ[n]:
            depth[m] = max(depth[m], depth[n] + 1)
            indeg[m] -= 1
            if indeg[m] == 0:
                queue.append(m)
    rows = {}
    for n in nodes:
        row = rows.get(depth[n], 0)
        rows[depth[n]] = row + 1
        n.location = (depth[n] * 220, -row * 180)


def ensure(name, build):
    """Node group `name`, (re)built when missing or from an older GROUP_VERSION."""
    ng = bpy.data.node_groups.get(name)
    if ng is None or ng.get(KEY_VERSION) != GROUP_VERSION:
        ng = build()
        arrange(ng)
    return ng


def geometry_group(name, inputs, body, menus=None, desc=""):
    """Lazy builder for a modifier-style group: Geometry + `inputs` -> Geometry.

    `body(b, g)` receives the builder and the group-input sockets and returns the output geometry.
    """
    def build():
        ng, gin, gout, b = new_group(name, [S("Geometry", "GEOMETRY")] + inputs, [S("Geometry", "GEOMETRY")], desc)
        b.link(body(b, gin.outputs), gout.inputs[0])
        set_menu_defaults(ng, menus or {})
        return ng
    return lambda: ensure(name, build)
